# Generated by Django 3.0.5 on 2020-04-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(default='2020-04-04 23:59:59.000000+03:00'),
        ),
    ]
