# Generated by Django 3.0.5 on 2020-04-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200404_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
