# Generated by Django 3.0.5 on 2020-04-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200404_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='media/images/default.png', upload_to='images/'),
        ),
    ]
